In [118]:
import pandas as pd

In [119]:
import numpy as np

In [120]:
x = pd.read_csv("ache.csv", sep = ";", low_memory=False)

In [121]:
x.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Target Type,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value
0,CHEMBL47375,NaN,None,332.85,0,2.10,1i,COc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],kHOX,'=',...,SINGLE PROTEIN,CHEMBL1123431,1,Scientific Literature,J Med Chem,1986.0,None,NaN,NaN,NaN
1,CHEMBL47375,NaN,None,332.85,0,2.10,1i,COc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],Rmax,NaN,...,SINGLE PROTEIN,CHEMBL1123431,1,Scientific Literature,J Med Chem,1986.0,None,NaN,NaN,NaN
2,CHEMBL45118,NaN,None,360.91,0,2.89,1j,CC[N+](C)(CC)CCS/C(=N\O)C(=O)c1ccc(OC)cc1.[Cl-],kHOX,'=',...,SINGLE PROTEIN,CHEMBL1123431,1,Scientific Literature,J Med Chem,1986.0,None,NaN,NaN,NaN
3,CHEMBL558598,RIMONABANT HYDROCHLORIDE,None,500.26,1,5.94,Rimonabant. Hydrochloride,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,'=',...,SINGLE PROTEIN,CHEMBL1156813,1,Scientific Literature,J Med Chem,2010.0,CHEMBL3307715,NaN,NaN,NaN
4,CHEMBL282468,CHOLINE CHLORIDE,4.0,139.63,None,None,CHOLINE CHLORIDE,C[N+](C)(C)CCO.[Cl-],Ki,NaN,...,SINGLE PROTEIN,CHEMBL1909046,15,DrugMatrix,NaN,NaN,CHEMBL3307715,NaN,NaN,NaN

In [122]:
x.shape

(18204, 47)

In [123]:
x.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value'],
      dtype='object')

In [124]:
y = x[['Molecule ChEMBL ID','Smiles','Standard Type','Standard Units','Standard Value']]

In [125]:
y.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
0,CHEMBL47375,COc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],kHOX,M-1 min-1,23.40
1,CHEMBL47375,COc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],Rmax,%,5.60
2,CHEMBL45118,CC[N+](C)(CC)CCS/C(=N\O)C(=O)c1ccc(OC)cc1.[Cl-],kHOX,M-1 min-1,32.40
3,CHEMBL558598,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,nM,25118.86
4,CHEMBL282468,C[N+](C)(C)CCO.[Cl-],Ki,NaN,NaN

In [126]:
y=y.dropna()

In [127]:
y.shape

(14298, 5)

In [128]:
y['Molecule ChEMBL ID'].value_counts()

CHEMBL502        215
CHEMBL95         211
CHEMBL659        105
CHEMBL33051       87
CHEMBL291233      84
                ...
CHEMBL4551728      1
CHEMBL4457932      1
CHEMBL3632989      1
CHEMBL496126       1
CHEMBL5078078      1
Name: Molecule ChEMBL ID, Length: 8847, dtype: int64

In [129]:
z=y[y['Molecule ChEMBL ID'].str.contains('CHEMBL502')]

In [130]:
z

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
62,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,50.12
79,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,Ki,nM,20.50
81,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,100000.00
275,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.00
339,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,22.91
...,...,...,...,...,...
17965,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.70
17971,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,Activity,%,53.60
17972,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,Activity,%,61.80
18083,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,7.39
18105,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,Inhibition,%,26.70

KeyError: 'Molecule CHEMBL ID'

In [131]:
y.columns

Index(['Molecule ChEMBL ID', 'Smiles', 'Standard Type', 'Standard Units',
       'Standard Value'],
      dtype='object')

In [132]:
y['Standard Units'].value_counts()

nM              10023
%                2703
/min              359
/mM/min           268
M-1 min-1         199
uM                108
mM/min             85
hr                 74
/M/min             55
ug.mL-1            39
min-1              36
M                  36
10'3/M/min         36
mM                 35
ug                 31
10e-3 1/s          28
min                23
s-1                19
10'-3/min          17
10^-3/min          16
ng                 16
/s                  8
/M/s                8
deltaA/min          6
10'4/M/min          6
/hr                 5
10'3L/M             4
10'5/M/min          4
10'5L/M             4
10'7/M/min          4
M-min               4
mAU/min             4
U/min               3
10'8/M/min          3
10'5pM              3
10'-1nmol           3
10'6pM              2
10'-4nmol           2
mm                  2
10^8M               2
10^-4microM         2
10'-8mol/min        2
10'-2nmol           2
degrees C           2
10'6/M/min          2
/min/M              1
10'2/M/min          1
10'3pM              1
nmol                1
%/hr                1
Name: Standard Units, dtype: int64

In [214]:
y_ = y[y['Standard Units'].str.contains("nM")]

In [215]:
y_.shape

(10023, 5)

In [223]:
y_.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
3,CHEMBL558598,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,nM,25118.86
7,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,50000.00
8,CHEMBL154211,N#CC(C#N)=C1NCCN1CCNCc1ccc(CN2CCCCC2)o1,IC50,nM,30.00
21,CHEMBL85473,COc1cc2cc(C(O)C3CC[N+](C)(Cc4ccccc4)CC3)sc2cc1...,IC50,nM,19580.00
23,CHEMBL3402707,CN(CCCCCN1C(=O)c2ccccc2C1=O)Cc1ccccc1.Cl,IC50,nM,361.00

In [224]:
y_['Standard Type'].value_counts()

IC50       7759
AC50        999
Ki          931
Kd          256
EC50         45
Kic           1
alphaKi       1
Name: Standard Type, dtype: int64

In [225]:
#Standard Type = [IC50,EC50,AC50, Ki, Kd and Potency]

In [226]:
y_['Standard Type'].str.contains("IC50|EC50|AC50|Ki|Kd|Potency")

3        True
7        True
8        True
21       True
23       True
         ...
18198    True
18199    True
18200    True
18201    True
18203    True
Name: Standard Type, Length: 9992, dtype: bool

In [227]:
y_ = y_[y_['Standard Type'].str.contains('IC50|EC50|AC50|Ki|Kd|Potency')]

In [228]:
y_

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
3,CHEMBL558598,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,nM,25118.86
7,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,50000.00
8,CHEMBL154211,N#CC(C#N)=C1NCCN1CCNCc1ccc(CN2CCCCC2)o1,IC50,nM,30.00
21,CHEMBL85473,COc1cc2cc(C(O)C3CC[N+](C)(Cc4ccccc4)CC3)sc2cc1...,IC50,nM,19580.00
23,CHEMBL3402707,CN(CCCCCN1C(=O)c2ccccc2C1=O)Cc1ccccc1.Cl,IC50,nM,361.00
...,...,...,...,...,...
18198,CHEMBL5220742,O=C1CCOc2cc(OCCCCCSC(=S)N3CCCCC3)ccc21,IC50,nM,100.00
18199,CHEMBL503160,O=C(O)/C=C/C(=O)O,AC50,nM,30000.00
18200,CHEMBL5202541,COc1cc(/C=C/c2cc(=O)oc3c2ccc2oc(-c4cccc(F)c4)c...,IC50,nM,1800.00
18201,CHEMBL3758997,NS(=O)(=O)c1ccc(/N=C/c2cc(Br)cc(Br)c2O)cc1,Ki,nM,21.00
18203,CHEMBL5078078,CC(C)(O)c1ccc(N2Cc3c(ccnc3-c3ccc(F)cc3OCC(F)(F...,IC50,nM,10000.00

In [229]:
y_.shape

(9992, 5)

In [230]:
y_.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
3,CHEMBL558598,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,nM,25118.86
7,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,50000.00
8,CHEMBL154211,N#CC(C#N)=C1NCCN1CCNCc1ccc(CN2CCCCC2)o1,IC50,nM,30.00
21,CHEMBL85473,COc1cc2cc(C(O)C3CC[N+](C)(Cc4ccccc4)CC3)sc2cc1...,IC50,nM,19580.00
23,CHEMBL3402707,CN(CCCCCN1C(=O)c2ccccc2C1=O)Cc1ccccc1.Cl,IC50,nM,361.00

In [234]:
y_['Standard Type'].value_counts()

IC50       7759
AC50        999
Ki          931
Kd          256
EC50         45
Kic           1
alphaKi       1
Name: Standard Type, dtype: int64

In [235]:
y_.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
3,CHEMBL558598,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,IC50,nM,25118.86
7,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,50000.00
8,CHEMBL154211,N#CC(C#N)=C1NCCN1CCNCc1ccc(CN2CCCCC2)o1,IC50,nM,30.00
21,CHEMBL85473,COc1cc2cc(C(O)C3CC[N+](C)(Cc4ccccc4)CC3)sc2cc1...,IC50,nM,19580.00
23,CHEMBL3402707,CN(CCCCCN1C(=O)c2ccccc2C1=O)Cc1ccccc1.Cl,IC50,nM,361.00

In [294]:
y_IC50 = y_[y_['Standard Type'].str.contains("IC50")]

In [295]:
y_IC50

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
5415,CHEMBL4780352,COc1cc2c(cc1OC)C(=O)/C(=C/c1ccc(OCCCCN[N+]3(C)...,IC50,nM,0.000000e+00
9059,CHEMBL199748,COc1ccc2[nH]cc(CCNC(=O)CCCCCNc3c4c(nc5cc(Cl)cc...,IC50,nM,5.000000e-06
8029,CHEMBL4543251,O=C(CCCCCNc1c2c(nc3ccc(F)cc13)CCCC2)NCCc1c[nH]...,IC50,nM,5.000000e-06
8028,CHEMBL4448350,O=C(CCCCCNc1c2c(nc3c(Cl)cccc13)CCCC2)NCCc1c[nH...,IC50,nM,5.000000e-06
14586,CHEMBL199585,O=C(CCCCCCNc1c2c(nc3cc(Cl)cc(Cl)c13)CCCC2)NCCc...,IC50,nM,5.000000e-06
...,...,...,...,...,...
491,CHEMBL3597055,COC(=O)C1=C(Nc2ccc(F)cc2)C[C@@H](c2ccccc2)N(c2...,IC50,nM,1.512000e+07
2438,CHEMBL1276534,O=C(NP(=O)(NN1CCOCC1)NN1CCOCC1)c1ccccc1,IC50,nM,1.862000e+07
5250,CHEMBL51628,O=c1ccc2ccc(O)cc2o1,IC50,nM,2.900000e+07
3962,CHEMBL371798,CN(CCCCCCCOc1ccc2c(c1)O/C(=C\c1cccc3ccccc13)C2...,IC50,nM,4.960000e+07
8773,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,5.000000e+07

In [296]:
y_IC50.shape

(7759, 5)

In [297]:
# Use Case #1: Finding new molecules against ACHE (CHEMBL220)
# Build bioactivity classifier, can classify new molecules from different database into active in inactive
# IC50/Ki/Kd... Smaller the value, stronger the inhibition/binding
# positive (active) and negative (inactive)

# active (positive) < 10 nM -> Label 1
# inactive (negative) > 20 nM -> Label 0

# Use Case #2: Finding new molecules based on bioactivity data
# Bioactivity regression model for predicting bioactivity value of new molecules 
# Binding affinity prediction

In [298]:
z = y_[y_["Molecule ChEMBL ID"].str.contains("CHEMBL502")]

In [299]:
z

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
275,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.00
4253,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.33
11735,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,4.00
15158,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.00
15653,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.59
...,...,...,...,...,...
16336,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,7560.00
13011,CHEMBL502620,CC[C@@]1(O)C[C@H](O[C@H]2C[C@H](N(C)C)[C@H](O[...,AC50,nM,30000.00
81,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,100000.00
13507,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,198000.00
8837,CHEMBL502689,CC(C)=CCc1cc2ccc(=O)oc2cc1O,IC50,nM,2400000.00

In [300]:
z.sort_values("Standard Value", ascending=True)

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
275,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.00
4253,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.33
11735,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,4.00
15158,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.00
15653,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.59
...,...,...,...,...,...
16336,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,7560.00
13011,CHEMBL502620,CC[C@@]1(O)C[C@H](O[C@H]2C[C@H](N(C)C)[C@H](O[...,AC50,nM,30000.00
81,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,100000.00
13507,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,198000.00
8837,CHEMBL502689,CC(C)=CCc1cc2ccc(=O)oc2cc1O,IC50,nM,2400000.00

In [301]:
y_.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
5415,CHEMBL4780352,COc1cc2c(cc1OC)C(=O)/C(=C/c1ccc(OCCCCN[N+]3(C)...,IC50,nM,0.000000
9059,CHEMBL199748,COc1ccc2[nH]cc(CCNC(=O)CCCCCNc3c4c(nc5cc(Cl)cc...,IC50,nM,0.000005
8029,CHEMBL4543251,O=C(CCCCCNc1c2c(nc3ccc(F)cc13)CCCC2)NCCc1c[nH]...,IC50,nM,0.000005
8028,CHEMBL4448350,O=C(CCCCCNc1c2c(nc3c(Cl)cccc13)CCCC2)NCCc1c[nH...,IC50,nM,0.000005
14586,CHEMBL199585,O=C(CCCCCCNc1c2c(nc3cc(Cl)cc(Cl)c13)CCCC2)NCCc...,IC50,nM,0.000005

In [302]:
y_IC50 = y_IC50.sort_values("Standard Value", ascending=True)

In [303]:
y_IC50.tail()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
491,CHEMBL3597055,COC(=O)C1=C(Nc2ccc(F)cc2)C[C@@H](c2ccccc2)N(c2...,IC50,nM,15120000.0
2438,CHEMBL1276534,O=C(NP(=O)(NN1CCOCC1)NN1CCOCC1)c1ccccc1,IC50,nM,18620000.0
5250,CHEMBL51628,O=c1ccc2ccc(O)cc2o1,IC50,nM,29000000.0
3962,CHEMBL371798,CN(CCCCCCCOc1ccc2c(c1)O/C(=C\c1cccc3ccccc13)C2...,IC50,nM,49600000.0
8773,CHEMBL131051,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)c1ccccc1,IC50,nM,50000000.0

In [304]:
y_IC50.shape

(7759, 5)

In [305]:
y_IC50 = y_IC50.drop_duplicates(subset='Molecule ChEMBL ID', keep='first')

In [306]:
y_IC50.shape

(6339, 5)

In [308]:
z['Standard Value'].mean()

17787.5911483871

In [313]:
z.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
275,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.00
4253,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.33
11735,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,4.00
15158,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.00
15653,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.59

In [311]:
x.iloc[122:124]

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Target Type,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value
122,CHEMBL11805,CAPROCTAMINE,None,666.99,2,7.65,3,COc1ccccc1CN(C)CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)...,IC50,'=',...,SINGLE PROTEIN,CHEMBL1145289,1,Scientific Literature,J Med Chem,2005.0,None,NaN,NaN,NaN
123,CHEMBL136052,NaN,None,402.67,1,5.44,32,CC(=O)N(C)[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC[C@H...,IC50,'=',...,SINGLE PROTEIN,CHEMBL1136484,1,Scientific Literature,Bioorg Med Chem Lett,2003.0,None,NaN,NaN,NaN

In [314]:
z.reset_index()

,index,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
0,275,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.00
1,4253,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,2.33
2,11735,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,4.00
3,15158,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.00
4,15653,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,5.59
...,...,...,...,...,...,...
150,16336,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,7560.00
151,13011,CHEMBL502620,CC[C@@]1(O)C[C@H](O[C@H]2C[C@H](N(C)C)[C@H](O[...,AC50,nM,30000.00
152,81,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,100000.00
153,13507,CHEMBL502,COc1cc2c(cc1OC)C(=O)C(CC1CCN(Cc3ccccc3)CC1)C2,IC50,nM,198000.00
154,8837,CHEMBL502689,CC(C)=CCc1cc2ccc(=O)oc2cc1O,IC50,nM,2400000.00

In [337]:
active = y_IC50.loc[y_IC50['Standard Value']<=10000]

In [338]:
active.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
5415,CHEMBL4780352,COc1cc2c(cc1OC)C(=O)/C(=C/c1ccc(OCCCCN[N+]3(C)...,IC50,nM,0.000000
14845,CHEMBL4468781,COc1ccc2[nH]cc(CCNC(=O)CCCCCNc3c4c(nc5cc(Cl)cc...,IC50,nM,0.000005
5703,CHEMBL4556734,O=C(CCCCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c...,IC50,nM,0.000005
13149,CHEMBL4443426,O=C(CCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2cc...,IC50,nM,0.000005
14171,CHEMBL4469239,S=C(CCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2c...,IC50,nM,0.000005

In [339]:
active.shape

(4531, 5)

In [340]:
inactive = y_IC50.loc[y_IC50['Standard Value']>=20000]

In [341]:
inactive.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value
17029,CHEMBL4250314,CCOc1cccc2c(=O)c3c(oc12)CCN(/C(=C/C(=O)OC)C(=O...,IC50,nM,20000.0
10182,CHEMBL155495,CNC(NCCNCc1ccc(COC)o1)=C(C#N)C#N,IC50,nM,20000.0
4241,CHEMBL4248378,CN1CCc2oc3ccc(Br)cc3c(=O)c2C1,IC50,nM,20000.0
3826,CHEMBL4538834,Cl.c1ccc(CCCCN2CCCc3[nH]c4ccccc4c3C2)cc1,IC50,nM,20000.0
9679,CHEMBL3087682,CC(C(=O)NCCCNC1=CC(=O)C(NCCCNC(=O)C(C)c2ccc(-c...,IC50,nM,20000.0

In [342]:
inactive.shape

(1419, 5)

In [344]:
active = active.assign(Label=1)

In [345]:
active.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value,Label
5415,CHEMBL4780352,COc1cc2c(cc1OC)C(=O)/C(=C/c1ccc(OCCCCN[N+]3(C)...,IC50,nM,0.000000,1
14845,CHEMBL4468781,COc1ccc2[nH]cc(CCNC(=O)CCCCCNc3c4c(nc5cc(Cl)cc...,IC50,nM,0.000005,1
5703,CHEMBL4556734,O=C(CCCCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c...,IC50,nM,0.000005,1
13149,CHEMBL4443426,O=C(CCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2cc...,IC50,nM,0.000005,1
14171,CHEMBL4469239,S=C(CCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2c...,IC50,nM,0.000005,1

In [346]:
inactive = inactive.assign(Label=0)

In [347]:
inactive.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value,Label
17029,CHEMBL4250314,CCOc1cccc2c(=O)c3c(oc12)CCN(/C(=C/C(=O)OC)C(=O...,IC50,nM,20000.0,0
10182,CHEMBL155495,CNC(NCCNCc1ccc(COC)o1)=C(C#N)C#N,IC50,nM,20000.0,0
4241,CHEMBL4248378,CN1CCc2oc3ccc(Br)cc3c(=O)c2C1,IC50,nM,20000.0,0
3826,CHEMBL4538834,Cl.c1ccc(CCCCN2CCCc3[nH]c4ccccc4c3C2)cc1,IC50,nM,20000.0,0
9679,CHEMBL3087682,CC(C(=O)NCCCNC1=CC(=O)C(NCCCNC(=O)C(C)c2ccc(-c...,IC50,nM,20000.0,0

In [348]:
combined = pd.concat([active, inactive], axis=0)

In [349]:
combined

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Units,Standard Value,Label
5415,CHEMBL4780352,COc1cc2c(cc1OC)C(=O)/C(=C/c1ccc(OCCCCN[N+]3(C)...,IC50,nM,0.000000e+00,1
14845,CHEMBL4468781,COc1ccc2[nH]cc(CCNC(=O)CCCCCNc3c4c(nc5cc(Cl)cc...,IC50,nM,5.000000e-06,1
5703,CHEMBL4556734,O=C(CCCCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c...,IC50,nM,5.000000e-06,1
13149,CHEMBL4443426,O=C(CCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2cc...,IC50,nM,5.000000e-06,1
14171,CHEMBL4469239,S=C(CCCCCNc1c2c(nc3ccccc13)CCCC2)NCCc1c[nH]c2c...,IC50,nM,5.000000e-06,1
...,...,...,...,...,...,...
11411,CHEMBL1276594,O=P(NN1CCOCC1)(NN1CCOCC1)Oc1ccccc1,IC50,nM,9.550000e+06,0
7569,CHEMBL102637,CCSC(=O)OCC[N+](C)(C)C.[Cl-],IC50,nM,1.000000e+07,0
324,CHEMBL334938,C[N+]1(C)CCO[C@@](O)(c2ccc(C#N)cc2)C1,IC50,nM,1.158777e+07,0
2438,CHEMBL1276534,O=C(NP(=O)(NN1CCOCC1)NN1CCOCC1)c1ccccc1,IC50,nM,1.862000e+07,0
3962,CHEMBL371798,CN(CCCCCCCOc1ccc2c(c1)O/C(=C\c1cccc3ccccc13)C2...,IC50,nM,4.960000e+07,0

In [351]:
combined.to_csv('ache labelled.csv', index=None)

In [352]:
combined[["Smiles", "Label"]].to_csv("ache_labelled.smiles", header=None, index=None, sep=",")

In [353]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is 42D6-0B4A

 Directory of C:\Users\karol\anaconda3\envs\myenv\Exploratory Data Analysis - Bioactivity Data

09/10/2024  08:49 PM    <DIR>          .
09/10/2024  11:43 AM    <DIR>          ..
09/10/2024  11:46 AM    <DIR>          .ipynb_checkpoints
09/10/2024  08:47 PM           501,392 ache labeled.csv
09/10/2024  11:40 AM        10,437,313 ache.csv
09/10/2024  08:49 PM           332,494 ache_labelled.smiles
09/10/2024  04:31 PM         3,866,802 Artigo1.pdf
09/10/2024  08:48 PM           119,819 Untitled.ipynb
               5 File(s)     15,257,820 bytes
               3 Dir(s)  211,612,774,400 bytes free